export const HIDE_RECIPE_MODAL = "HIDE_RECIPE_MODAL";
export const SHOW_RECIPE_MODAL = "SHOW_RECIPE_MODAL";
export const SEARCH_BY_RECIPE_NAME = "SEARCH_BY_RECIPE_NAME";
export const HIDE_FILTER_MODAL = "HIDE_FILTER_MODAL";
export const SHOW_FILTER_MODAL = "SHOW_FILTER_MODAL";
export const SET_ACTIVE_FILTER = "SET_ACTIVE_FILTER";
